admin.layout_box.index:
    path: /admin/layout/box/index
    defaults:
        _controller: 'layout_box.controller.admin:indexAction'
    options:
        require_admin_permission: layout_box.index
admin.layout_box.grid:
    path: /admin/layout/box/grid
    defaults:
        _controller: 'layout_box.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: layout_box.index
admin.layout_box.add:
    path: /admin/layout/box/add
    defaults:
        _controller: 'layout_box.controller.admin:addAction'
    options:
        require_admin_permission: layout_box.add
admin.layout_box.edit:
    path: '/admin/layout/box/edit/{id}'
    defaults:
        _controller: 'layout_box.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: layout_box.edit
admin.layout_box.delete:
    path: '/admin/layout/box/delete/{id}'
    defaults:
        _controller: 'layout_box.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: layout_box.delete
