# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    layout_box.renderer:
        class: WellCommerce\Bundle\LayoutBundle\Renderer\LayoutBoxRenderer
        arguments: ['@layout_box.service_resolver', '@layout_box.manager', '@router.helper']

    layout_box.subscriber:
        class: WellCommerce\Bundle\LayoutBundle\EventListener\LayoutBoxSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    layout_box.service_resolver:
        class: WellCommerce\Bundle\LayoutBundle\Resolver\ServiceResolver
        arguments: ['@layout_box.configurator.collection']
        calls:
            - [setContainer, ['@service_container']]

    layout_box.configurator.collection:
        class: WellCommerce\Bundle\LayoutBundle\Configurator\LayoutBoxConfiguratorCollection

    twig.extension.layout_box:
        class: WellCommerce\Bundle\LayoutBundle\Twig\Extension\LayoutBoxExtension
        tags:
            - { name: twig.extension }
        arguments: ['@layout_box.renderer']
