# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\LayoutBundle\Entity\LayoutBoxInterface: WellCommerce\Bundle\LayoutBundle\Entity\LayoutBox

well_commerce_doctrine:
    configuration:
        layout_box:
            factory: WellCommerce\Bundle\LayoutBundle\Factory\LayoutBoxFactory
            repository: WellCommerce\Bundle\LayoutBundle\Repository\LayoutBoxRepository
            mapping: "@WellCommerceLayoutBundle/Resources/config/doctrine/LayoutBox.orm.yml"
            entity: WellCommerce\Bundle\LayoutBundle\Entity\LayoutBox
        layout_box_translation:
            manager: false
            mapping: "@WellCommerceLayoutBundle/Resources/config/doctrine/LayoutBoxTranslation.orm.yml"
            entity: WellCommerce\Bundle\LayoutBundle\Entity\LayoutBoxTranslation
